#!/bin/bash

# Pair this script with with start_capture.sh. {Still in Development}

today=$(date +"%Y-%m-%d")
PID=$(pgrep -n start_capture)
echo 'The PID of start_capture is' "$PID"
echo 'Killing Process now'
kill -15 "$PID"

SERVICE="start_capture.sh"
if pgrep -x "$SERVICE" >/dev/null
then
    echo "$SERVICE is running"
else
    echo "$SERVICE stopped"
    tcpdump -tttt -r /root/capturedLog_${today}.pcap >> /root/readableLog_${today}.txt
fi
