#!/bin/bash
# telnet to hostname/ip at a port to check presence of a listener

function connect_to() {
perl -MIO::Socket -e '$socket=IO::Socket::INET->new(Proto=>tcp,PeerAddr=>$ARGV[0],PeerPort=>$ARGV[1],Timeout=>5);if($@){ printf("%s to port %s at %s\n", $@, $ARGV[1], $ARGV[0]) } else { printf("Connection to port %s at %s Succeeded\n", $ARGV[1], $ARGV[0]); }' $1 $2
}

connect_to $1  $2
